include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unused_element: ignore

linter:
  rules:
    file_names: false
    use_build_context_synchronously: false
    prefer_const_constructors_in_immutables: false
