// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2OOpC7U9dPG_dXrQzO9gOTiZbDxq72Kc',
    appId: '1:250885591484:web:950f8edeb1f8340f939bb9',
    messagingSenderId: '250885591484',
    projectId: 'divulgapampa-86896',
    authDomain: 'divulgapampa-86896.firebaseapp.com',
    storageBucket: 'divulgapampa-86896.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFvhFeMSRBEyW5T9YZ968IXmvfn2qTWRw',
    appId: '1:250885591484:android:4f651ffa0a83d90c939bb9',
    messagingSenderId: '250885591484',
    projectId: 'divulgapampa-86896',
    storageBucket: 'divulgapampa-86896.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnh_y-Az3k71-qGQsjBOBy3fQ6ZlObSOw',
    appId: '1:250885591484:ios:7ef123c5a6ddf121939bb9',
    messagingSenderId: '250885591484',
    projectId: 'divulgapampa-86896',
    storageBucket: 'divulgapampa-86896.firebasestorage.app',
    iosBundleId: 'com.astracode.divulgapampa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnh_y-Az3k71-qGQsjBOBy3fQ6ZlObSOw',
    appId: '1:250885591484:ios:7ef123c5a6ddf121939bb9',
    messagingSenderId: '250885591484',
    projectId: 'divulgapampa-86896',
    storageBucket: 'divulgapampa-86896.firebasestorage.app',
    iosBundleId: 'com.astracode.divulgapampa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2OOpC7U9dPG_dXrQzO9gOTiZbDxq72Kc',
    appId: '1:250885591484:web:eaa2b67b818a72fb939bb9',
    messagingSenderId: '250885591484',
    projectId: 'divulgapampa-86896',
    authDomain: 'divulgapampa-86896.firebaseapp.com',
    storageBucket: 'divulgapampa-86896.firebasestorage.app',
  );

}